### ISSUE TITLE
Sky deck (sonic) cannon tracking glitch

### ISSUE THREAD

**Issue by Labreezy** [X-Hax/sadx-mod-loader#89] opened 2021-10-29 00:20 UTC
The SADX speedrunning community has noticed a glitch for a while that only happens on mod loader versions past 171 (circa 2018).  The cannon in sonic's sky deck will not immediately lock on to his position, and as a result the rocket that's supposed to explode it can miss.  This is probably a nuisance for speedrunners more than casual players, but I'd like to at least know if this is a wontfix or if it has a solution besides "don't update the manager".

**Comment by MainMemory** [comment] 2021-10-29 18:50
This version of the mod loader won't use BASS for music or voices. [SADXModLoader.zip](https://github.com/X-Hax/sadx-mod-loader/files/7444313/SADXModLoader.zip)

**Comment by skewbmaster** [comment] 2021-10-29 19:35
I don't think this issue is tied to a fault in the base game, and dismissing it as such is clearly jumping to conclusions.

For years now runners have been stuck with the old 2018 build of the mod loader due to this oversight, every single instance of where the cannon glitch occurred was either due to accidentally updating the mod loader to whatever was latest or changing sound files to anything but wma types. This isn't a recent issue, it's been happening for years.

Meanwhile, I've done several tests with both versions of the mod loader - each with different file scenarios:

Old Mod Loader:
- Removed BGM files - No glitch
- Base game - No glitch
- BGM files including ADX or WAV - Glitch with certain sound files

Latest Mod Loader:
- Removed BGM files - No glitch
- Base game - Glitch
- BGM files including ADX or WAV - Glitch

[Video Proof](https://youtu.be/tP5iwOErOh0)

Our main problem is of course, the base game having the glitch 100% of the time on anything newer. Aside from "anecdotal reports", Refrag's video detailing the issue clearly shows the glitch happening on the new loader multiple times, all the time; with the only exceptions being the ones where they waited for the cannon to move down (which works). In speedruns we don't wait!

What we are seeing from the real results is that audio playback may play some role in this. As much as common sense would lead anyone to believe, audio and gameplay shouldn't relate to each other. However, assuming that could shy away from where the problem lies.

> I've played the game many times with the Mod Loader over the years and only run into this glitch a few times

If by years you mean anything roughly before 2019, you would've played on versions where this glitch doesn't even happen. At the same time there's no proof you couldn't have waited the time it takes the cannon to put itself in the "working" position.

> I have encountered this glitch in the PC version without the Mod Loader, as well as the Dreamcast and Gamecube versions.

We would also like proof of this actually happening, in just the same way it can be considered an anecdotal report.




Edit: Main replied as I was wrote this up with a fix, I'm glad you found that BASS is the problem and we'd like to see it as an option in the later versions.

**Comment by MainMemory** [comment] 2021-10-29 19:38
So it does fix the bug? I don't understand how, the game isn't relying on audio playback for timing, and it doesn't play any sound when you fire the rocket.

**Comment by skewbmaster** [comment] 2021-10-29 19:42
We're as confused as you, but it does indeed fix everything.

**Comment by PiKeyAr** [comment] 2021-10-29 22:38
Interesting videos that clearly show a correlation. Let me clarify a few things in your comments.


>I don't think this issue is tied to a fault in the base game, and dismissing it as such is clearly jumping to conclusions.


It happens, although rarely, in the Dreamcast and Gamecube versions of the game, hence it's a fault in the base game. The Mod Loader or BASS don't cause the issue per se, but for some reason they make it worse, as the videos have demonstrated. I cannot tell you why, at least not yet. I'm just pointing out that the `only happens on mod loader versions past 171` as claimed by the original post is incorrect. Also, I've provided the address of the function that works unreliably. You can look at its disassembled code and see the logical error at the end of the calculation. You can also try to write a mod to cover the missing distance range (or just return the "right" value all the time), which would be the real fix for this problem. Although there is a correlation, disabling BASS doesn't fix the original issue which lies in the game's logic.


>Our main problem is of course, the base game having the glitch 100% of the time on anything newer.


Like you admit, it has to be a certain timing and the rocket must not be facing down. This glitch is actually not that common, and there has to be a combination of conditions to trigger it. So it's not 100% of the time.


>If by years you mean anything roughly before 2019, you would've played on versions where this glitch doesn't even happen. At the same time there's no proof you couldn't have waited the time it takes the cannon to put itself in the "working" position.


2016 to 2021. I didn't attempt to speedrun the game, and since this glitch is rather rare in casual gameplay this explains why I didn't run into it as often as you did.


I would like to keep this issue open because I'm interested in what influences this "race condition" if we can call it such, and if I'm wrong about the function I want to know what the actual issue is.

**Comment by cglmrfreeman** [comment] 2021-10-30 02:45
For the sake of clarification (because I find this whole thing absolutely fascinating), what is the difference in Sonic making the "YEAAAHHHH!" in the first, non-mod-loader, half of the video, and the second half of the video where Sonic says nothing and the glitch occurs. I might be missing something obvious involving the "BASS" audio, but I'm merely curious why it isn't triggering in the second half.

**Comment by PiKeyAr** [comment] 2021-10-30 06:12
As far as I could tell, that plays after the code to destroy the cannon, so if the cannon is not destroyed it's not played.


The current working idea is that the BASS version used by the Mod Loader affects [floating point math behavior](http://www.un4seen.com/forum/?topic=19062.0), which causes the results of distance calculations in the speedrunning scenario to fall more consistently within the range not accounted for by the game.

**Comment by PiKeyAr** [comment] 2021-10-30 07:13
Could you try with this? This is a version of the Mod Loader from before the fix but using a more recent build of BASS.
[ml.zip](https://github.com/X-Hax/sadx-mod-loader/files/7446001/ml.zip)

**Comment by cglmrfreeman** [comment] 2021-11-18 20:05
Has this build been tested by those interested in seeing this fixed? Feedback would be nice instead of leaving this issue hanging out in the open.

**Comment by ItsEasyActually** [comment] 2021-12-12 22:34
BASS was confirmed to be causing some errors with floating point values which led to an increased frequency in this glitch occurring.  This was resolved by updating BASS for the ModManager. The option to disable BASS is also available in the ModManager if the user would rather disable it entirely. 

Reference Commits:
7757dcd2a2f5a3ee120717bf3935b85a14285fd2 - Disable BASS Option Added
a1a6bcaed0033836276e8509da9463a00d9e70e0 - Updated BASS

Seeing as how this has been resolved for a bit, I'm closing the issue.

**Closed by ItsEasyActually** 2021-12-12 22:34 UTC
