### ISSUE TITLE
Some remaining material colors issues

### ISSUE THREAD

**Issue by LimitCrown** [X-Hax/sadx-mod-loader#58] opened 2019-09-03 15:22 UTC
A previous update to the mod loader fixed some issues pertaining to vertex and material colors. However, this has affected the Chao Transporter's appearance in a strange way.
![sonic_2019-09-03_10-44-41](https://user-images.githubusercontent.com/24856516/64186033-24118b80-ce3c-11e9-8018-9d5d0bb57b2e.png)
Some objects in the game like the table in Eggman's study still appear to have different colors as well when compared with GC SADX.
![sonic_2019-09-03_11-17-33](https://user-images.githubusercontent.com/24856516/64186487-ea8d5000-ce3c-11e9-9756-c41b9a58003e.png)

**Comment by PiKeyAr** [comment] 2019-09-03 15:51
The previous update restored usage of object vertex colors. Material colors are still used as vertex colors for models that don't have vertex colors built in, which happens to be the case with the majority of models in the game.

I've long been recommending to completely ignore material colors in the renderer (like GC and DC versions do), as they are often nonsensical and cause loss of detail and/or intended looks in 99% of cases. However, it's also been suggested that material colors can potentially be used in a mod, so completely ignoring them seems like loss of a feature. Because of this, material colors are currently still not ignored.

One potential way to deal with this (for whoever might be interested) is to fix it manually by going through all problematic models and replacing their material diffuse with white.

**Comment by LimitCrown** [comment] 2019-09-03 17:31
Ah, I see.

**Comment by michael-fadely** [comment] 2019-09-03 22:35
If you notice any other related oddities, please do let me know. I don't want this to have a negative visual impact on the game, it already has enough problems =P

**Comment by PiKeyAr** [comment] 2022-05-05 06:19
Fixed in [this commit](https://github.com/X-Hax/sadx-mod-loader/commit/735f49b8fdb6a6e1f819701a5fdaaeba0af01075). All material colors should look right now. The Chao Transporter isn't affected by this fix because the issue isn't caused by material colors - the vertex colors in model data are set up that way.
![image](https://user-images.githubusercontent.com/23312549/166871358-788cf210-6209-4cc0-b694-b8edb9857334.png)

**Closed by PiKeyAr** 2022-05-05 06:19 UTC
