### ISSUE TITLE
Replacetex folders exported from DX texture files do not translate properly to DC texture files

### ISSUE THREAD

**Issue by Mal2026** [X-Hax/sadx-mod-loader#122] opened 2023-04-26 20:28 UTC
I am currently trying to port someone's texture mod to work with DC conversion via the replacetex method. After exporting the textures (again, from a DX pvmx) into replacetex, I noticed that not all of the textures were properly replaced when loaded up with DC conversion enabled. Some textures ended up in unintended places and others just did not show up at all. I believe this may be because different textures may be assigned to different names but I do not know if that is 100% true. I am trying to do some troubleshooting but I feel it would be best to report this issue. I hope I was clear enough. 

Attached is a DX pvmx that I am trying to work on to fully work with DC conversion. Please export this into a replacetex folder in a mod and boot up the game on DC conversion and without and you will see what I mean. 

[ADV_MR00.zip](https://github.com/X-Hax/sadx-mod-loader/files/11336970/ADV_MR00.zip)

**Comment by MainMemory** [comment] 2023-04-27 14:26
Upon further examination this is a problem caused by the differences in the textures between vanilla DX and DC Conversion, not a bug in the mod loader. Closing.

**Closed by MainMemory** 2023-04-27 14:26 UTC
