### ISSUE TITLE
Pachacamac Texture Bug

### ISSUE THREAD

**Issue by ElectroNuke** [X-Hax/sadx-mod-loader#121] opened 2023-04-18 21:44 UTC
So, this texture bug seems relatively new. Apparently, Pachacamac's leaf necklace is now a blank white after I updated the mod loader. I've tried disabling each of my mods, but the issue persists. I'm not sure if this is specifically a mod loader problem, but I figured it was worth addressing. See the added screenshots for the bug in action and my full list of mods.

P.S. I've tried disabling the vertex color, material color, and interpolation fixes. Still no luck.

![64359a12cd336](https://user-images.githubusercontent.com/33000916/232912071-5de32721-3cd4-4709-8a9c-57ac0ce3c902.jpg)

**Comment by PiKeyAr** [comment] 2023-04-19 10:31
Unfortunately the lighting shown here is technically "correct" as far as I can tell. The reason this didn't happen in the vanilla PC version is because SADX PC has a bug that causes it to reset the light type used for characters when the character model is put in the draw queue. As a result, in the vanilla version some parts of Pachacamac's model use lighting that is not meant for characters. However, if the light type is set correctly (which happens whenever the Mod Loader is enabled), the cranked up SADXPC character specular lighting in combination with the model's normals make it look fullbright.
At the moment the Mod Manager does not expose the option to disable the light type fix, and I don't know if an option like that will be made available.

**Comment by cheatfreak47** [comment] 2023-04-19 10:34
If a lighting "fix" introduces a regression it should probably be made optional or have some kind of workaround put in place for this specific case

**Comment by PiKeyAr** [comment] 2023-04-19 10:45
I don't consider this a regression since this is how it would've looked if the vanilla game's lighting system was less broken. There's an argument for making the fix optional, but there are also complaints about having too many options in the Mod Manager so I don't know. 

I personally don't mind moving this fix back to the Lantern Engine mod where it was originally introduced, but there's been a discussion about fixes that could be moved over from Lantern Engine and Dreamcast Conversion to the Mod Loader to improve the base game, and this was one of them. I didn't know about this one instance in the game where it actually makes something look worse than vanilla.

**Comment by PiKeyAr** [comment] 2024-02-10 10:08
This can now be turned off with the "Light fixes" patch in the Game Config/Patches tab in the new manager.

**Closed by PiKeyAr** 2024-02-10 10:08 UTC
